# Generated by Django 3.0.7 on 2020-06-19 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default='media/images/profile_pics/default.png', upload_to='media/images/profile_pics/'),
        ),
    ]
